apiVersion: v1
kind: Service
metadata:
    name: clientservice
    namespace: nsjiraproject
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer