apiVersion: v1
kind: Service
metadata:
    name: apiservice
    namespace: nsjiraproject
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP